-- Priemerné hodnotenie filmov podľa žánru
SELECT g.GENRE_NAME, AVG(f.AVG_RATING) AS AVERAGE_RATING
FROM FACT_MOVIES f
JOIN DIM_GENRES g ON f.GENRE_ID = g.DIM_GENREID
GROUP BY g.GENRE_NAME
ORDER BY AVERAGE_RATING DESC;

-- Počet filmov v databáze
SELECT COUNT(f.FACT_MOVIE_ID) AS MOVIE_COUNT
FROM FACT_MOVIES f;

-- Počet filmov podľa žánru v priebehu rokov
SELECT m.YEAR, g.GENRE_NAME, COUNT(f.FACT_MOVIE_ID) AS MOVIE_COUNT
FROM FACT_MOVIES f
JOIN DIM_MOVIES m ON f.MOVIE_ID = m.DIM_MOVIEID
JOIN DIM_GENRES g ON f.GENRE_ID = g.DIM_GENREID
GROUP BY m.YEAR, g.GENRE_NAME
ORDER BY m.YEAR, MOVIE_COUNT DESC;

-- Počet filmov podľa režiséra a žánru
SELECT d.NAME AS DIRECTOR_NAME, g.GENRE_NAME, COUNT(f.FACT_MOVIE_ID) AS MOVIE_COUNT
FROM FACT_MOVIES f
JOIN DIM_DIRECTORS d ON f.DIRECTOR_ID = d.DIRECTOR_ID
JOIN DIM_GENRES g ON f.GENRE_ID = g.DIM_GENREID
GROUP BY d.NAME, g.GENRE_NAME
ORDER BY MOVIE_COUNT DESC;

-- Top 5 filmov s najvyšším počtom hlasov
SELECT m.TITLE, SUM(f.TOTAL_VOTES) AS TOTAL_VOTES
FROM FACT_MOVIES f
JOIN DIM_MOVIES m ON f.MOVIE_ID = m.DIM_MOVIEID
GROUP BY m.TITLE
ORDER BY TOTAL_VOTES DESC
LIMIT 5;

-- Výška hercov vs. Počet filmov, v ktorých sa objavili
SELECT n.HEIGHT, COUNT(f.FACT_MOVIE_ID) AS MOVIE_COUNT
FROM FACT_MOVIES f
JOIN DIM_NAMES n ON f.NAME_ID = n.DIM_NAMEID
GROUP BY n.HEIGHT
ORDER BY n.HEIGHT;
